server:
  port: 8080

spring:
  cloud:
    gateway:
#      default-filters:
#      - name: CustomFilter
      routes:
      - id: employeeModule
        uri: http://localhost:8081/
        predicates:
        - Path=/employee/**
        filters:
#          - CustomFilter
        - AddRequestHeader=first-request, first-request-header
        - AddResponseHeader=first-response, first-response-header
      - id: consumerModule
        uri: http://localhost:8082/
        predicates:
        - Path=/consumer/**
        filters:
#          - CustomFilter
        - AddRequestHeader=second-request, second-request-header
        - AddResponseHeader=second-response, second-response-header